# name=input("What Yours name?")
# Address=input("Where do you live?")
# Age=input("How old are u?")
# num1= int(input ("First number:"))
# num2=int(input ("Second number:"))
# add=num1 + num2
# print(add)
num1= input ("First number:")
num2=input ("Second number:")
add=int(num1) + int(num2)
print(add)